app/Http/routes.php
<?php

use Illuminate\Routing\Router;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect(route('admin.expenditure.shopping.index'));
});

Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/profile/{id}', ['as' => 'profile', 'uses' => 'User\UserController@profile']);
    $router->post('/profile/update/{id}', ['as' => 'profile.update', 'uses' => 'User\UserController@updateProfile']);
});

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/', ['as' => 'home', 'uses' => 'DefaultController@index']);

    $router->group([
        'namespace' => 'User'
    ], function (Router $router) {
        $router->get('/users', ['as' => 'users', 'uses' => 'UserController@index']);
    });

    $router->group([
        'namespace' => 'Group'
    ], function (Router $router) {
        $router->get('/groups', ['as' => 'groups', 'uses' => 'GroupController@index']);
    });

    $router->group([
        'namespace' => 'Role'
    ], function (Router $router) {
        $router->get('/roles', ['as' => 'roles', 'uses' => 'RoleController@index']);
    });

    $router->group([
        'as' => 'expenditure.',
        'prefix' => 'expenditure',
        'namespace' => 'Expenditure'
    ], function (Router $router) {
        $router->get('/group', ['as' => 'group.index', 'uses' => 'GroupController@index']);
        $router->get('/group/{id}', ['as' => 'group.detail', 'uses' => 'GroupController@detail']);
        $router->get('/shopping', ['as' => 'shopping.index', 'uses' => 'ShoppingController@index']);
    });

});

Route::group([
    'as' => 'api.',
    'prefix' => 'api',
], function (Router $router) {

    /*
     * ====================
     * Frontend Routing
     * ===================
     */


    /*
     * ====================
     * Backend Routing
     * ===================
     */
    $router->group([
        'as' => 'be.',
        'prefix' => 'be',
        'namespace' => 'Backend',
        'middleware' => ['auth']
    ], function (Router $router) {
        $router->group([
            'as' => 'user.',
            'prefix' => 'user',
            'namespace' => 'User'
        ], function (Router $router) {
            $router->post('/users', ['as' => 'getAllUser', 'uses' => 'UserController@getAllUser']);
            $router->post('/', ['as' => 'create', 'uses' => 'UserController@create']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'UserController@delete']);
            $router->get('/getEditUserModal/{id}', ['as' => 'getEditUserModal', 'uses' => 'UserController@getEditUserModal']);
            $router->get('/getDeleteUserModal/{id}', ['as' => 'getDeleteUserModal', 'uses' => 'UserController@getDeleteUserModal']);
        });

        $router->group([
            'as' => 'group.',
            'prefix' => 'group',
            'namespace' => 'Group'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'GroupController@create']);
            $router->get('/{id}', ['as' => 'get', 'uses' => 'GroupController@get']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'GroupController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'GroupController@delete']);
            $router->get('/query/{query}', ['as' => 'query', 'uses' => 'GroupController@queryMember']);
            $router->get('/getDeleteGroupModal/{id}', ['as' => 'getDeleteGroupModal', 'uses' => 'GroupController@getDeleteGroupModal']);
        });

        $router->group([
            'as' => 'role.',
            'prefix' => 'role',
            'namespace' => 'Role'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'RoleController@create']);
        });
        
        $router->group([
            'as' => 'expenditure.',
            'prefix' => 'expenditure',
            'namespace' => 'Expenditure'
        ], function (Router $router){
            $router->post('/group', ['as' => 'group.create', 'uses' => 'GroupController@create']);
            $router->put('/group', ['as' => 'group.update', 'uses' => 'GroupController@update']);
            $router->delete('/group', ['as' => 'group.delete', 'uses' => 'GroupController@delete']);
            $router->group([
                'as' => 'shopping.',
                'prefix' => 'shopping',
            ], function (Router $router){
                $router->post('/{group_id}', ['as' => 'create', 'uses' => 'ShoppingController@create']);
                $router->put('/{group_id}/{shopping_id}', ['as' => 'update', 'uses' => 'ShoppingController@update']);
                $router->delete('/{group_id}/{shopping_id}', ['as' => 'delete', 'uses' => 'ShoppingController@delete']);
                $router->post('/refresh/{group_id}', ['as' => 'refresh', 'uses' => 'ShoppingController@refresh']);
                $router->get('/getCreateShoppingModal/{id}', ['as' => 'getCreateShoppingModal', 'uses' => 'ShoppingController@getCreateShoppingModal']);
                $router->get('/getEditShoppingModal/{group_id}/{shopping_id}', ['as' => 'getEditShoppingModal', 'uses' => 'ShoppingController@getEditShoppingModal']);
                $router->get('/getDeleteShoppingModal/{group_id}/{shopping_id}', ['as' => 'getDeleteShoppingModal', 'uses' => 'ShoppingController@getDeleteShoppingModal']);
                $router->get('/getRefreshShoppingModal/{group_id}', ['as' => 'getRefreshShoppingModal', 'uses' => 'ShoppingController@getRefreshShoppingModal']);
            });
        });

        $router->group([
            'as' => 'datatable.',
            'prefix' => 'datatable',
            'namespace' => 'Datatable'
        ], function (Router $router) {
            $router->get('/i18n', ['as' => 'i18n', 'uses' => 'DatatableController@i18n']);
        });
    });


});

Route::group([
    'as' => 'auth.',
    'prefix' => 'auth',
    'namespace' => 'Auth'
], function (Router $router) {
    $router->get('facebook', ['as' => 'facebook', 'uses' => 'SocialAuthController@redirectToFacebook']);
    $router->get('facebook/callback',
        ['as' => 'facebook.callback', 'uses' => 'SocialAuthController@handleFacebookCallback']);

    $router->get('google', ['as' => 'google', 'uses' => 'SocialAuthController@redirectToGoogle']);
    $router->get('google/callback',
        ['as' => 'google.callback', 'uses' => 'SocialAuthController@handleGoogleCallback']);

    $router->get('twitter', ['as' => 'twitter', 'uses' => 'SocialAuthController@redirectToTwitter']);
    $router->get('twitter/callback',
        ['as' => 'twitter.callback', 'uses' => 'SocialAuthController@handleTwitterCallback']);

    $router->get('github', ['as' => 'github', 'uses' => 'SocialAuthController@redirectToGithub']);
    $router->get('github/callback',
        ['as' => 'github.callback', 'uses' => 'SocialAuthController@handleGithubCallback']);
});

Route::auth();

app/Http/Controllers/Backend/Expenditure/GroupController.php
<?php

namespace App\Http\Controllers\Backend\Expenditure;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Eloquent\Group;
use Illuminate\Support\Facades\Gate;

class GroupController extends Controller
{

    public function index(){
        $user = Auth::user();
        $user->groups;
        
        return view('backend.expenditure.group.index', [
            'groups' => $user->groups
        ]);
    }

    /**
     * Show detail shopping about 1 group by id
     * @param $id
     */
    public function detail($id){
        $user = Auth::user();
        $group = Group::find($id);

        if(Gate::allows('isAdministrator', $user) && $group){
            $group->members;
            $shoppings = $group->shoppings;
            foreach ($shoppings as $shopping) {
                $shopping->users;
                $shopping->purchaser;
            }
        }else{
            return redirect(env('APP_URL', '/'));
        }

        $groups = [];
        array_push($groups, $group);

        return view('backend.expenditure.shopping.index', [
            'groups' => $groups
        ]);

    }

}

app/Http/Controllers/Backend/Group/GroupController.php
<?php

namespace App\Http\Controllers\Backend\Group;

use App\Eloquent\Group;
use App\Eloquent\User;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;

class GroupController extends Controller
{
    /**
     * Show the group management page.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::with('monitor')->with('members')->get();

        return view('backend.group.index', [
            'groups' => $groups
        ]);
    }

    /**
     * Query coresponding data for typeheadjs
     * GET /api/be/group/query/{query}
     * @param $query
     * @return \Illuminate\Http\JsonResponse
     */
    public function queryMember($query)
    {
        $members = User::where('email', 'like', '%' . $query . '%')
            ->orWhere('name', 'like', '%' . $query . '%')
            ->orderBy('name', 'asc')
            ->get();

        return response()->json([
            'members' => $members,
        ]);
    }

    /**
     * Get group info
     * GET /api/be/group/{id}
     * @param $id
     * @return \Illuminate\Http\JsonResponse|void
     */
    public function get($id)
    {
        $group = Group::with('monitor')->with('members')->find($id);

        if (!$group) {
            return abort(404);
        }

        return response()->json([
            'status' => true,
            'data' => [
                'msg' => '',
                'group' => $group
            ]
        ]);
    }

    /**
     * Create new group
     * POST /api/be/group
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function create(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'monitor_id' => 'required',
        ]);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        $name = $request->input('name');
        $monitor_id = $request->input('monitor_id');
        $members_id = explode(',', $request->input('members_id'));

        $group = Group::create([
            'name' => $name,
            'monitor_id' => $monitor_id,
        ]);


        if (!in_array($monitor_id, $members_id)) {
            array_push($members_id, $monitor_id);
        }

        $group->members()->attach($members_id);

        Flash::success(trans('be/group.msg.create.success'));
        return redirect()->back();
    }

    /**
     * Get Delete Group Confirmation Modal
     * GET /api/be/user/getDeleteGroupModal
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|void
     */
    public function getDeleteGroupModal($id)
    {
        $group = Group::find($id);

        if (!$group) {
            return abort(404);
        }

        $msg = trans('be/common.modal.delete_confirmation.group');
        $action = env('APP_URL') . '/api/be/group/' . $id;

        return view('partials.delete_confirmation', [
            'group' => $group,
            'msg' => $msg,
            'action' => $action
        ]);
    }

    /**
     * Delete group and corresponding roles
     * DELETE /api/be/group/{id}
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function delete($id)
    {
        $group = Group::find($id);

        if (!$group) {
            return abort(404);
        }

        $group->members()->detach();
        $group->delete();

        Flash::success(trans('be/group.msg.delete.success'));
        return redirect()->back();
    }

    /**
     * Update group info
     * PUT /api/be/group/{id}
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function update($id, Request $request)
    {
        $group = Group::find($id);
        
        if(!$group){
            return abort(404);
        }
        
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'monitor_id' => 'required',
        ]);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        $name = $request->input('name');
        $monitor_id = $request->input('monitor_id');
        $members_id = explode(',', $request->input('members_id'));

        $group->name = $name;
        $group->monitor_id = $monitor_id;

        $group->save();

        if (!in_array($monitor_id, $members_id)) {
            array_push($members_id, $monitor_id);
        }

        $group->members()->detach();
        $group->members()->attach($members_id);

        Flash::success(trans('be/group.msg.update.success'));
        return redirect()->back();
    }

}

resources/views/backend/expenditure/group/modal/create.blade.php
<div class="modal fade ieg-modal-container add-group-modal typehead-modal-element" id="add-group-modal">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@lang('be/group.modal.create')</h4>
                </div>
                <form role="form" class="form-horizontal" action="{{ route('api.be.group.create') }}" method="post">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/group.modal.name')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control name" name="name" required>
                            </div>
                        </div>
                        <div class="form-group" hidden>
                            <label class="control-label col-sm-3">@lang('be/group.modal.monitor')</label>
                            <div class="col-sm-7">
                                <div class="remote">
                                    <input class="form-control" type="text" placeholder="@lang('be/group.modal.monitor_placeholder')" name="monitor_id" value="{{ Auth::user()->id }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/group.modal.member')</label>
                            <div class="col-sm-7">
                                <input class="members form-control" type="text" placeholder="@lang('be/group.modal.monitor_placeholder')" name="members_id" data-role="tagsinput">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default"
                                    data-dismiss="modal">@lang('be/common.button.cancel')</button>
                            <button type="button"
                                    class="btn btn-primary btn-save">@lang('be/common.button.save')</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/backend/expenditure/group/modal/edit.blade.php
<div class="modal fade ieg-modal-container edit-group-modal typehead-modal-element" id="edit-group-modal">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@lang('be/group.modal.edit')</h4>
                </div>
                <form role="form" class="form-horizontal" action="" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/group.modal.name')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control name" name="name" required>
                            </div>
                        </div>
                        <div class="form-group" hidden>
                            <label class="control-label col-sm-3">@lang('be/group.modal.monitor')</label>
                            <div class="col-sm-7">
                                <div class="remote">
                                    <input class="typeahead monitor form-control" type="text"
                                           placeholder="@lang('be/group.modal.monitor_placeholder')"
                                           name="monitor_id" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/group.modal.member')</label>
                            <div class="col-sm-7">
                                <input class="members form-control" type="text"
                                       placeholder="@lang('be/group.modal.monitor_placeholder')"
                                       name="members_id" data-role="tagsinput">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default"
                                    data-dismiss="modal">@lang('be/common.button.cancel')</button>
                            <button type="button"
                                    class="btn btn-primary btn-save">@lang('be/common.button.save')</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>