app/Http/routes.php
<?php

use Illuminate\Routing\Router;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect(route('admin.expenditure.shopping.index'));
});

Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/profile/{id}', ['as' => 'profile', 'uses' => 'User\UserController@profile']);
    $router->post('/profile/update/{id}', ['as' => 'profile.update', 'uses' => 'User\UserController@updateProfile']);
});

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/', ['as' => 'home', 'uses' => 'DefaultController@index']);

    $router->group([
        'namespace' => 'User'
    ], function (Router $router) {
        $router->get('/users', ['as' => 'users', 'uses' => 'UserController@index']);
    });

    $router->group([
        'namespace' => 'Group'
    ], function (Router $router) {
        $router->get('/groups', ['as' => 'groups', 'uses' => 'GroupController@index']);
    });

    $router->group([
        'namespace' => 'Role'
    ], function (Router $router) {
        $router->get('/roles', ['as' => 'roles', 'uses' => 'RoleController@index']);
    });

    $router->group([
        'as' => 'expenditure.',
        'prefix' => 'expenditure',
        'namespace' => 'Expenditure'
    ], function (Router $router) {
        $router->get('/group', ['as' => 'group.index', 'uses' => 'GroupController@index']);
        $router->get('/group/{id}', ['as' => 'group.detail', 'uses' => 'GroupController@detail']);
        $router->get('/shopping', ['as' => 'shopping.index', 'uses' => 'ShoppingController@index']);
    });

});

Route::group([
    'as' => 'api.',
    'prefix' => 'api',
], function (Router $router) {

    /*
     * ====================
     * Frontend Routing
     * ===================
     */


    /*
     * ====================
     * Backend Routing
     * ===================
     */
    $router->group([
        'as' => 'be.',
        'prefix' => 'be',
        'namespace' => 'Backend',
        'middleware' => ['auth']
    ], function (Router $router) {
        $router->group([
            'as' => 'user.',
            'prefix' => 'user',
            'namespace' => 'User'
        ], function (Router $router) {
            $router->post('/users', ['as' => 'getAllUser', 'uses' => 'UserController@getAllUser']);
            $router->post('/', ['as' => 'create', 'uses' => 'UserController@create']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'UserController@delete']);
            $router->get('/getEditUserModal/{id}', ['as' => 'getEditUserModal', 'uses' => 'UserController@getEditUserModal']);
            $router->get('/getDeleteUserModal/{id}', ['as' => 'getDeleteUserModal', 'uses' => 'UserController@getDeleteUserModal']);
        });

        $router->group([
            'as' => 'group.',
            'prefix' => 'group',
            'namespace' => 'Group'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'GroupController@create']);
            $router->get('/{id}', ['as' => 'get', 'uses' => 'GroupController@get']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'GroupController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'GroupController@delete']);
            $router->get('/query/{query}', ['as' => 'query', 'uses' => 'GroupController@queryMember']);
            $router->get('/getDeleteGroupModal/{id}', ['as' => 'getDeleteGroupModal', 'uses' => 'GroupController@getDeleteGroupModal']);
        });

        $router->group([
            'as' => 'role.',
            'prefix' => 'role',
            'namespace' => 'Role'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'RoleController@create']);
        });
        
        $router->group([
            'as' => 'expenditure.',
            'prefix' => 'expenditure',
            'namespace' => 'Expenditure'
        ], function (Router $router){
            $router->post('/group', ['as' => 'group.create', 'uses' => 'GroupController@create']);
            $router->put('/group', ['as' => 'group.update', 'uses' => 'GroupController@update']);
            $router->delete('/group', ['as' => 'group.delete', 'uses' => 'GroupController@delete']);
            $router->group([
                'as' => 'shopping.',
                'prefix' => 'shopping',
            ], function (Router $router){
                $router->post('/{group_id}', ['as' => 'create', 'uses' => 'ShoppingController@create']);
                $router->put('/{group_id}/{shopping_id}', ['as' => 'update', 'uses' => 'ShoppingController@update']);
                $router->delete('/{group_id}/{shopping_id}', ['as' => 'delete', 'uses' => 'ShoppingController@delete']);
                $router->post('/refresh/{group_id}', ['as' => 'refresh', 'uses' => 'ShoppingController@refresh']);
                $router->get('/getCreateShoppingModal/{id}', ['as' => 'getCreateShoppingModal', 'uses' => 'ShoppingController@getCreateShoppingModal']);
                $router->get('/getEditShoppingModal/{group_id}/{shopping_id}', ['as' => 'getEditShoppingModal', 'uses' => 'ShoppingController@getEditShoppingModal']);
                $router->get('/getDeleteShoppingModal/{group_id}/{shopping_id}', ['as' => 'getDeleteShoppingModal', 'uses' => 'ShoppingController@getDeleteShoppingModal']);
                $router->get('/getRefreshShoppingModal/{group_id}', ['as' => 'getRefreshShoppingModal', 'uses' => 'ShoppingController@getRefreshShoppingModal']);
            });
        });

        $router->group([
            'as' => 'datatable.',
            'prefix' => 'datatable',
            'namespace' => 'Datatable'
        ], function (Router $router) {
            $router->get('/i18n', ['as' => 'i18n', 'uses' => 'DatatableController@i18n']);
        });
    });


});

Route::group([
    'as' => 'auth.',
    'prefix' => 'auth',
    'namespace' => 'Auth'
], function (Router $router) {
    $router->get('facebook', ['as' => 'facebook', 'uses' => 'SocialAuthController@redirectToFacebook']);
    $router->get('facebook/callback',
        ['as' => 'facebook.callback', 'uses' => 'SocialAuthController@handleFacebookCallback']);

    $router->get('google', ['as' => 'google', 'uses' => 'SocialAuthController@redirectToGoogle']);
    $router->get('google/callback',
        ['as' => 'google.callback', 'uses' => 'SocialAuthController@handleGoogleCallback']);

    $router->get('twitter', ['as' => 'twitter', 'uses' => 'SocialAuthController@redirectToTwitter']);
    $router->get('twitter/callback',
        ['as' => 'twitter.callback', 'uses' => 'SocialAuthController@handleTwitterCallback']);

    $router->get('github', ['as' => 'github', 'uses' => 'SocialAuthController@redirectToGithub']);
    $router->get('github/callback',
        ['as' => 'github.callback', 'uses' => 'SocialAuthController@handleGithubCallback']);
});

Route::auth();

app/Http/Controllers/Backend/Datatable/DatatableController.php
<?php

namespace App\Http\Controllers\Backend\Datatable;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class DatatableController extends Controller
{

    public function i18n(){
        $vietnamese = File::get(storage_path() . '/data/dataTables.vi.lang.json');
        
        return $vietnamese;
    }

}

app/Http/Controllers/Backend/DefaultController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DefaultController extends Controller
{
    /**
     * Show the admin dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect(route('admin.expenditure.shopping.index'));
    }
}

app/Http/Controllers/Backend/Expenditure/ExpenditureController.php
<?php

namespace App\Http\Controllers\Backend\Expenditure;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ExpenditureController extends Controller
{

    public function index(){
        
    }

}

app/Http/Controllers/Backend/Expenditure/GroupController.php
<?php

namespace App\Http\Controllers\Backend\Expenditure;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Eloquent\Group;
use Illuminate\Support\Facades\Gate;

class GroupController extends Controller
{

    public function index(){
        $user = Auth::user();
        $user->groups;
        
        return view('backend.expenditure.group.index', [
            'groups' => $user->groups
        ]);
    }

    /**
     * Show detail shopping about 1 group by id
     * @param $id
     */
    public function detail($id){
        $user = Auth::user();
        $group = Group::find($id);

        if(Gate::allows('isAdministrator', $user) && $group){
            $group->members;
            $shoppings = $group->shoppings;
            foreach ($shoppings as $shopping) {
                $shopping->users;
                $shopping->purchaser;
            }
        }else{
            return redirect(env('APP_URL', '/'));
        }

        $groups = [];
        array_push($groups, $group);

        return view('backend.expenditure.shopping.index', [
            'groups' => $groups
        ]);

    }

}

app/Http/Controllers/Backend/Expenditure/ShoppingController.php
<?php

namespace App\Http\Controllers\Backend\Expenditure;

use App\Eloquent\Group;
use App\Eloquent\GroupUserShopping;
use App\Eloquent\Shopping;
use App\Eloquent\Time;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;

class ShoppingController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $groups = isset($user->groups) ? $user->groups : '';

        if (count($groups) == 0) {
            return redirect(route('admin.expenditure.group.index'));
        }

        foreach ($groups as $group) {
            $group->members;
            $shoppings = $group->shoppings;
            foreach ($shoppings as $shopping) {
                $shopping->users;
                $shopping->purchaser;
            }
        }

        return view('backend.expenditure.shopping.index', [
            'groups' => $groups
        ]);
    }

    public function getCreateShoppingModal($group_id)
    {
        $group = Group::find($group_id);

        if (!$group) {
            return abort(404);
        }

        $group->members;
        $action = env('APP_URL') . '/api/be/expenditure/shopping/' . $group_id;

        return view('backend.expenditure.shopping.modal.create', [
            'group' => $group,
            'action' => $action
        ]);
    }

    public function create($group_id, Request $request)
    {

        $validator = Validator::make($request->all(), [
            'member' => 'required',
            'money' => 'required',
            'relates' => 'required'
        ]);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        $shopping = '';
        $relates = $request->input('relates');
        if (count($relates) > 1) {
            $shopping = Shopping::create([
                'group_id' => $group_id,
                'user_id' => $request->input('member'),
                'money' => $request->input('money'),
                'description' => $request->input('description'),
                'status' => 1,
                'date' => Carbon::createFromFormat('d/m/Y', $request->input('date')),
            ]);

            $money = $request->input('money') / count($relates);
            foreach ($relates as $id) {
                $shopping->users()->attach($id, [
                    'money' => $request->input('member') == $id ? (count($relates) - 1) * $money : (-1) * $money
                ]);
            }
        } else {
            Flash::warning(trans('be/shopping.msg.relate'));
            return redirect()->back();
        }

        Flash::success(trans('be/shopping.msg.create.success'));
        return redirect()->back();
    }

    public function getEditShoppingModal($group_id, $shopping_id)
    {
        $group = Group::find($group_id);
        $shopping = Shopping::find($shopping_id);

        if (!$group || !$shopping) {
            return abort(404);
        }

        $group->members;
        $shopping->purchaser;
        $action = env('APP_URL') . '/api/be/expenditure/shopping/' . $group_id . '/' . $shopping_id;

        return view('backend.expenditure.shopping.modal.edit', [
            'group' => $group,
            'shopping' => $shopping,
            'action' => $action
        ]);
    }

    public function update($group_id, $shopping_id, Request $request)
    {

        $validator = Validator::make($request->all(), [
            'member' => 'required',
            'money' => 'required',
            'relates' => 'required'
        ]);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        $shopping = Shopping::find($shopping_id);
        $relates = $request->input('relates');
        if (count($relates) > 1) {
            $shopping->user_id = $request->input('member');
            $shopping->money = $request->input('money');
            $shopping->description = $request->input('description');
            $shopping->date = Carbon::createFromFormat('d/m/Y', $request->input('date'));

            $shopping->save();

            $money = $request->input('money') / count($relates);
            $shopping->users()->detach();
            foreach ($relates as $id) {
                $shopping->users()->attach($id, [
                    'money' => $request->input('member') == $id ? (count($relates) - 1) * $money : (-1) * $money
                ]);
            }
        } else {
            Flash::warning(trans('be/shopping.msg.relate'));
            return redirect()->back();
        }

        Flash::success(trans('be/shopping.msg.update.success'));
        return redirect()->back();
    }

    public function getDeleteShoppingModal($group_id, $shopping_id)
    {
        $group = Group::find($group_id);
        $shopping = Shopping::find($shopping_id);

        if (!$group || !$shopping) {
            return abort(404);
        }

        $group->members;
        $action = env('APP_URL') . '/api/be/expenditure/shopping/' . $group_id . '/' . $shopping_id;
        $msg = trans('be/common.modal.delete_confirmation.shopping');

        return view('partials.delete_confirmation', [
            'shopping' => $shopping,
            'action' => $action,
            'msg' => $msg
        ]);
    }

    public function delete($group_id, $shopping_id)
    {
        $group = Group::find($group_id);
        $shopping = Shopping::find($shopping_id);

        if (!$group || !$shopping) {
            return abort(404);
        }

        $shopping->delete();
        $shopping->users()->detach();

        Flash::success(trans('be/shopping.msg.delete.success'));
        return redirect()->back();
    }

    public function getRefreshShoppingModal($group_id)
    {
        $group = Group::find($group_id);

        if (!$group) {
            return abort(404);
        }

        $action = env('APP_URL') . '/api/be/expenditure/shopping/refresh/' . $group_id;
        $method = 'post';
        $msg = trans('be/shopping.modal.refresh');

        return view('partials.delete_confirmation', [
            'action' => $action,
            'method' => $method,
            'msg' => $msg
        ]);
    }

    public function refresh($group_id)
    {
        $group = Group::find($group_id);

        if (!$group) {
            return abort(404);
        }

        Time::create([
            'group_id' => $group_id,
            'time' => date("Y-m-d H:i:s")
        ]);

        Flash::success(trans('be/shopping.msg.update.success'));
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Role/RoleController.php
<?php

namespace App\Http\Controllers\Backend\Role;

use App\Http\Requests;
use App\Eloquent\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Show all roles in role management page.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        
        return view('backend.role.index', [
            'roles' => $roles
        ]);
    }
    
    public function create(Request $request){
        
    }
}

resources/views/backend/user/index.blade.php
@extends('backend.layout.default')

@section('title')
    @lang('be/user.manage_user')
@endsection

@section('content')
    <section class="content-header">
        <h1>@lang('be/user.manage_user')</h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
            {{--flash message--}}
                <div class="flash-notification">
                    @include('partials.flash_message')
                </div>
            <!-- /.box -->
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-responsive" id="rms-user-table">
                            <thead>
                            <tr>
                                <th>@lang('be/user.email')</th>
                                <th>@lang('be/user.name')</th>
                                <th>@lang('be/user.role')</th>
                                <th>@lang('be/user.created_at')</th>
                                <th>@lang('be/user.action')</th>
                            </tr>
                            </thead>
                        </table>
                        <div class="menu-bottom">
                            <div class="btn-group">
                                <button id="add-user" title="Add new user" type="button" class="btn btn-success"
                                        data-toggle="modal"
                                        data-target="#add-user-modal"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <div class="ieg-modal-container">
        <div class="create">
            @include('backend.user.modal.create')
        </div>
        <div class="edit">

        </div>
        <div class="delete">

        </div>
    </div>
@endsection

resources/views/backend/user/profile.blade.php
@extends('backend.layout.default')

@section('title')
    @lang('be/user.manage_user')
@endsection

@section('content')
    <section class="content-header">
        <h1>Thông tin tài khoản</h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                {{--flash message--}}
                <div class="flash-notification">
                    @include('partials.flash_message')
                </div>
                <!-- /.box -->
                <div class="box">
                    <form role="form" class="form-horizontal" action="{{ route('user.profile.update', $user->id) }}" method="post">
                        {{ csrf_field() }}
                        <div class="modal-body">
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.password')</label>
                                <div class="col-sm-7">
                                    <input type="password" class="form-control password" name="password" title="( Mật khẩu để trống nếu không muốn thay đổi. )">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.password_confirmation')</label>
                                <div class="col-sm-7">
                                    <input type="password" class="form-control password-confirmation"
                                           name="password_confirmation" title="( Mật khẩu để trống nếu không muốn thay đổi. )">
                                </div>
                            </div>
                            <div class="form-group">
                                <hr>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.name')</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control name" name="name" value="{{ $user->name }}" required>
                                </div>
                                <span class="star">(*)</span>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.gender.title')</label>
                                <div class="col-sm-7">
                                    <select class="form-control" id="user-role" name="gender">
                                        <option value="">@lang('be/user.modal.select_gender')</option>
                                        <option value="1" {{ $user->gender == 1 ? 'selected' : '' }}>@lang('be/user.modal.gender.male')</option>
                                        <option value="2" {{ $user->gender == 2 ? 'selected' : '' }}>@lang('be/user.modal.gender.female')</option>
                                        <option value="3" {{ $user->gender == 3 ? 'selected' : '' }}>@lang('be/user.modal.gender.other')</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.birthday')</label>
                                <div class="col-sm-7">
                                    <input data-provide="datepicker" data-date-format="yyyy/mm/dd" type="text" class="form-control birthday" name="birthday" value="{{ $user->birthday }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.address')</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control address" name="address" value="{{ $user->address }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.phone')</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control phone" name="phone" value="{{ $user->phone }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">@lang('be/user.modal.about')</label>
                                <div class="col-sm-7">
                                    <textarea type="text" class="form-control about" name="about" rows="4">{{ $user->about }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer" style="text-align: center;">
                            <button type="submit" class="btn btn-primary btn-save"
                                    data-type="event">@lang('be/common.button.save')</button>
                        </div>
                    </form>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection