app/Http/routes.php
<?php

use Illuminate\Routing\Router;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect(route('admin.expenditure.shopping.index'));
});

Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/profile/{id}', ['as' => 'profile', 'uses' => 'User\UserController@profile']);
    $router->post('/profile/update/{id}', ['as' => 'profile.update', 'uses' => 'User\UserController@updateProfile']);
});

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => ['auth'],
    'namespace' => 'Backend'
], function (Router $router) {
    $router->get('/', ['as' => 'home', 'uses' => 'DefaultController@index']);

    $router->group([
        'namespace' => 'User'
    ], function (Router $router) {
        $router->get('/users', ['as' => 'users', 'uses' => 'UserController@index']);
    });

    $router->group([
        'namespace' => 'Group'
    ], function (Router $router) {
        $router->get('/groups', ['as' => 'groups', 'uses' => 'GroupController@index']);
    });

    $router->group([
        'namespace' => 'Role'
    ], function (Router $router) {
        $router->get('/roles', ['as' => 'roles', 'uses' => 'RoleController@index']);
    });

    $router->group([
        'as' => 'expenditure.',
        'prefix' => 'expenditure',
        'namespace' => 'Expenditure'
    ], function (Router $router) {
        $router->get('/group', ['as' => 'group.index', 'uses' => 'GroupController@index']);
        $router->get('/group/{id}', ['as' => 'group.detail', 'uses' => 'GroupController@detail']);
        $router->get('/shopping', ['as' => 'shopping.index', 'uses' => 'ShoppingController@index']);
    });

});

Route::group([
    'as' => 'api.',
    'prefix' => 'api',
], function (Router $router) {

    /*
     * ====================
     * Frontend Routing
     * ===================
     */


    /*
     * ====================
     * Backend Routing
     * ===================
     */
    $router->group([
        'as' => 'be.',
        'prefix' => 'be',
        'namespace' => 'Backend',
        'middleware' => ['auth']
    ], function (Router $router) {
        $router->group([
            'as' => 'user.',
            'prefix' => 'user',
            'namespace' => 'User'
        ], function (Router $router) {
            $router->post('/users', ['as' => 'getAllUser', 'uses' => 'UserController@getAllUser']);
            $router->post('/', ['as' => 'create', 'uses' => 'UserController@create']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'UserController@delete']);
            $router->get('/getEditUserModal/{id}', ['as' => 'getEditUserModal', 'uses' => 'UserController@getEditUserModal']);
            $router->get('/getDeleteUserModal/{id}', ['as' => 'getDeleteUserModal', 'uses' => 'UserController@getDeleteUserModal']);
        });

        $router->group([
            'as' => 'group.',
            'prefix' => 'group',
            'namespace' => 'Group'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'GroupController@create']);
            $router->get('/{id}', ['as' => 'get', 'uses' => 'GroupController@get']);
            $router->put('/{id}', ['as' => 'update', 'uses' => 'GroupController@update']);
            $router->delete('/{id}', ['as' => 'delete', 'uses' => 'GroupController@delete']);
            $router->get('/query/{query}', ['as' => 'query', 'uses' => 'GroupController@queryMember']);
            $router->get('/getDeleteGroupModal/{id}', ['as' => 'getDeleteGroupModal', 'uses' => 'GroupController@getDeleteGroupModal']);
        });

        $router->group([
            'as' => 'role.',
            'prefix' => 'role',
            'namespace' => 'Role'
        ], function (Router $router) {
            $router->post('/', ['as' => 'create', 'uses' => 'RoleController@create']);
        });
        
        $router->group([
            'as' => 'expenditure.',
            'prefix' => 'expenditure',
            'namespace' => 'Expenditure'
        ], function (Router $router){
            $router->post('/group', ['as' => 'group.create', 'uses' => 'GroupController@create']);
            $router->put('/group', ['as' => 'group.update', 'uses' => 'GroupController@update']);
            $router->delete('/group', ['as' => 'group.delete', 'uses' => 'GroupController@delete']);
            $router->group([
                'as' => 'shopping.',
                'prefix' => 'shopping',
            ], function (Router $router){
                $router->post('/{group_id}', ['as' => 'create', 'uses' => 'ShoppingController@create']);
                $router->put('/{group_id}/{shopping_id}', ['as' => 'update', 'uses' => 'ShoppingController@update']);
                $router->delete('/{group_id}/{shopping_id}', ['as' => 'delete', 'uses' => 'ShoppingController@delete']);
                $router->post('/refresh/{group_id}', ['as' => 'refresh', 'uses' => 'ShoppingController@refresh']);
                $router->get('/getCreateShoppingModal/{id}', ['as' => 'getCreateShoppingModal', 'uses' => 'ShoppingController@getCreateShoppingModal']);
                $router->get('/getEditShoppingModal/{group_id}/{shopping_id}', ['as' => 'getEditShoppingModal', 'uses' => 'ShoppingController@getEditShoppingModal']);
                $router->get('/getDeleteShoppingModal/{group_id}/{shopping_id}', ['as' => 'getDeleteShoppingModal', 'uses' => 'ShoppingController@getDeleteShoppingModal']);
                $router->get('/getRefreshShoppingModal/{group_id}', ['as' => 'getRefreshShoppingModal', 'uses' => 'ShoppingController@getRefreshShoppingModal']);
            });
        });

        $router->group([
            'as' => 'datatable.',
            'prefix' => 'datatable',
            'namespace' => 'Datatable'
        ], function (Router $router) {
            $router->get('/i18n', ['as' => 'i18n', 'uses' => 'DatatableController@i18n']);
        });
    });


});

Route::group([
    'as' => 'auth.',
    'prefix' => 'auth',
    'namespace' => 'Auth'
], function (Router $router) {
    $router->get('facebook', ['as' => 'facebook', 'uses' => 'SocialAuthController@redirectToFacebook']);
    $router->get('facebook/callback',
        ['as' => 'facebook.callback', 'uses' => 'SocialAuthController@handleFacebookCallback']);

    $router->get('google', ['as' => 'google', 'uses' => 'SocialAuthController@redirectToGoogle']);
    $router->get('google/callback',
        ['as' => 'google.callback', 'uses' => 'SocialAuthController@handleGoogleCallback']);

    $router->get('twitter', ['as' => 'twitter', 'uses' => 'SocialAuthController@redirectToTwitter']);
    $router->get('twitter/callback',
        ['as' => 'twitter.callback', 'uses' => 'SocialAuthController@handleTwitterCallback']);

    $router->get('github', ['as' => 'github', 'uses' => 'SocialAuthController@redirectToGithub']);
    $router->get('github/callback',
        ['as' => 'github.callback', 'uses' => 'SocialAuthController@handleGithubCallback']);
});

Route::auth();

app/Http/Controllers/Backend/User/UserController.php
<?php

namespace App\Http\Controllers\Backend\User;

use App\Eloquent\Role;
use App\Http\Requests;
use App\Eloquent\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;

class UserController extends Controller
{
    /**
     * Show all users in user management page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('backend.user.index', [
            'roles' => $roles
        ]);
    }

    /**
     * Show user profile page
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function profile($id)
    {
        $user = Auth::user();

        if($user->id != $id){
            return redirect('/');
        }

        return view('backend.user.profile', [
            'user' => $user
        ]);
    }

    /**
     * Update User Profile Info
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function updateProfile($id, Request $request)
    {
        $user = Auth::user();

        if($user->id != $id){
            return redirect('/');
        }

        $rules = [
            'name' => 'required'
        ];

        if($request->input('password')){
            $rules["password"] = 'min:6|confirmed';
        }

        $messages = [
            'password_confirmation.same' => trans('be/validation.user.password_confirmation.same'),
            'name.required' => trans('be/validation.user.name.required'),
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        if($request->input('password')){
            $user->password = bcrypt($request->input('password'));
        }
        $user->name = $request->input('name');
        $user->gender = $request->input('gender');
        $user->birthday = $request->input('birthday');
        $user->address = $request->input('address');
        $user->phone = $request->input('phone');
        $user->about = $request->input('about');

        $user->save();

        Flash::success(trans('be/user.msg.update.success'));
        return redirect()->back();
    }

    /**
     * Get all users with their corresponding roles
     * POST : /api/be/user/users
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAllUser(Request $request)
    {
        $users = User::all();

        $totalData = count($users);
        $totalFiltered = $totalData;

        $users = User::with('roles')->orderBy('created_at', 'desc')
            ->skip($request['start'])
            ->take($request['length'])
            ->get();

        return response()->json([
            'draw' => $request->input('draw'),
            'search_value' => $request['search']['value'],
            'recordsTotal' => $totalData,
            'recordsFiltered' => $totalFiltered,
            'data' => $users,
        ]);
    }

    /**
     * Create new user
     * POST /api/be/user
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function create(Request $request)
    {

        $rules = [
            'email' => 'email|unique:users|required',
            'password' => 'min:6|required',
            'password_confirmation' => 'min:6|required|same:password',
            'name' => 'required'
        ];

        $messages = [
            'email.email' => trans('be/validation.user.email.email'),
            'email.unique' => trans('be/validation.user.email.unique'),
            'email.required' => trans('be/validation.user.email.required'),
            'password.min' => trans('be/validation.user.password.min'),
            'password.required' => trans('be/validation.user.password.required'),
            'password_confirmation.min' => trans('be/validation.user.password_confirmation.min'),
            'password_confirmation.required' => trans('be/validation.user.password_confirmation.required'),
            'password_confirmation.same' => trans('be/validation.user.password_confirmation.same'),
            'name.required' => trans('be/validation.user.name.required'),
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        $user = User::create([
            'email' => $request->input('email'),
            'password' => bcrypt($request->input('password')),
            'name' => $request->input('name'),
            'gender' => $request->input('gender'),
            'birthday' => $request->input('birthday'),
            'address' => $request->input('address'),
            'phone' => $request->input('phone'),
            'about' => $request->input('about'),
        ]);

        $role = $request->input('role');
        if ($role) {
            $user->roles()->attach($request->input('role'));
        }

        Flash::success(trans('be/user.msg.create.success'));
        return redirect()->back();
    }

    /**
     * Get Edit User Modal
     * GET /api/be/user/getEditUserModal
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|void
     */
    public function getEditUserModal($id)
    {
        $user = User::with('roles')->find($id);

        if (!$user) {
            return abort(404);
        }

        $roles = Role::all();
        $action = env('APP_URL') . '/api/be/user/' . $id;

        return view('backend.user.modal.edit', [
            'user' => $user,
            'roles' => $roles,
            'action' => $action
        ]);
    }

    /**
     * Get Delete User Modal
     * GET /api/be/user/getDeleteUserModal
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|void
     */
    public function getDeleteUserModal($id)
    {
        $user = User::find($id);

        if (!$user) {
            return abort(404);
        }

        $msg = trans('be/common.modal.delete_confirmation.user');
        $action = env('APP_URL') . '/api/be/user/' . $id;

        return view('partials.delete_confirmation', [
            'user' => $user,
            'msg' => $msg,
            'action' => $action
        ]);
    }

    /**
     * Update user info
     * PUT /api/be/user/{id}
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {

        $user = User::find($id);

        $rules = [
            'password_confirmation' => 'same:password',
            'name' => 'required'
        ];

        $messages = [
            'password_confirmation.same' => trans('be/validation.user.password_confirmation.same'),
            'name.required' => trans('be/validation.user.name.required'),
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            Flash::error($validator->errors()->first());
            return redirect()->back();
        }

        if($request->input('password')){
            $user->password = bcrypt($request->input('password'));
        }
        $user->name = $request->input('name');
        $user->gender = $request->input('gender');
        $user->birthday = $request->input('birthday');
        $user->address = $request->input('address');
        $user->phone = $request->input('phone');
        $user->about = $request->input('about');

        $user->save();

        $role = $request->input('role');
        if ($role) {
            $user->roles()->detach();
            $user->roles()->attach($request->input('role'));
        }

        Flash::success(trans('be/user.msg.update.success'));
        return redirect()->back();
    }

    /**
     * Delete user and corresponding roles
     * DELETE /api/be/user/{id}
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function delete($id)
    {
        $user = User::find($id);

        if (!$user) {
            return abort(404);
        }

        $user->roles()->detach();
        $user->delete();

        Flash::success(trans('be/user.msg.delete.success'));
        return redirect()->back();
    }
}

resources/views/backend/user/modal/create.blade.php
<div class="modal fade ieg-modal-container add-user-modal" id="add-user-modal">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@lang('be/user.modal.create')</h4>
                </div>
                <form role="form" class="form-horizontal" action="{{ route('api.be.user.create') }}" method="post">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.email')</label>
                            <div class="col-sm-7">
                                <input type="email" class="form-control email" name="email" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.role')</label>
                            <div class="col-sm-7">
                                <select class="form-control" id="user-role" name="role" required>
                                    <option value="">@lang('be/user.modal.select_role')</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.password')</label>
                            <div class="col-sm-7">
                                <input type="password" class="form-control password" name="password" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.password_confirmation')</label>
                            <div class="col-sm-7">
                                <input type="password" class="form-control password-confirmation"
                                       name="password_confirmation" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-7">
                                <label><input type="checkbox"> @lang('be/user.modal.lock_temporary') </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <hr>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.name')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control name" name="name" required>
                            </div>
                            <span class="star">(*)</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.gender.title')</label>
                            <div class="col-sm-7">
                                <select class="form-control" id="user-role" name="gender">
                                    <option value="">@lang('be/user.modal.select_gender')</option>
                                    <option value="1">@lang('be/user.modal.gender.male')</option>
                                    <option value="2">@lang('be/user.modal.gender.female')</option>
                                    <option value="3">@lang('be/user.modal.gender.other')</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.birthday')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control birthday" name="birthday">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.address')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control address" name="address">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.phone')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control phone" name="phone">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.about')</label>
                            <div class="col-sm-7">
                                <textarea type="text" class="form-control about" name="about" rows="4"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">@lang('be/common.button.cancel')</button>
                        <button type="submit" class="btn btn-primary btn-save"
                                data-type="event">@lang('be/common.button.save')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/backend/user/modal/edit.blade.php
<div class="modal fade ieg-modal-container edit-user-modal" id="edit-user-modal">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@lang('be/user.modal.edit')</h4>
                </div>
                <form role="form" class="form-horizontal" action="{{ $action }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.email')</label>
                            <div class="col-sm-7">
                                <input type="email" class="form-control email" name="email" value="{{ $user->email }}" disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.role')</label>
                            <div class="col-sm-7">
                                <select class="form-control" id="user-role" name="role" required>
                                    <option value="">@lang('be/user.modal.select_role')</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}" {{ count($user->roles) > 0 && $user->roles->first()->id == $role->id ? 'selected' : '' }}>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.password')</label>
                            <div class="col-sm-7">
                                <input type="password" class="form-control password" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.password_confirmation')</label>
                            <div class="col-sm-7">
                                <input type="password" class="form-control password-confirmation"
                                       name="password_confirmation">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-7">
                                <label><input type="checkbox" {{ $user->status == 0 ? 'checked' : '' }}> @lang('be/user.modal.lock_temporary') </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <hr>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.name')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control name" name="name" value="{{ $user->name }}" required>
                            </div>
                            <span class="star">(*)</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.gender.title')</label>
                            <div class="col-sm-7">
                                <select class="form-control" id="user-role" name="gender">
                                    <option value="">@lang('be/user.modal.select_gender')</option>
                                    <option value="1" {{ $user->gender == 1 ? 'selected' : '' }}>@lang('be/user.modal.gender.male')</option>
                                    <option value="2" {{ $user->gender == 2 ? 'selected' : '' }}>@lang('be/user.modal.gender.female')</option>
                                    <option value="3" {{ $user->gender == 3 ? 'selected' : '' }}>@lang('be/user.modal.gender.other')</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.birthday')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control birthday" name="birthday" value="{{ $user->birthday }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.address')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control address" name="address" value="{{ $user->address }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.phone')</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control phone" name="phone" value="{{ $user->phone }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">@lang('be/user.modal.about')</label>
                            <div class="col-sm-7">
                                <textarea type="text" class="form-control about" name="about" rows="4">{{ $user->about }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">@lang('be/common.button.cancel')</button>
                        <button type="submit" class="btn btn-primary btn-save"
                                data-type="event">@lang('be/common.button.save')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>